# Generated by Django 4.2.7 on 2023-12-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
