# Generated by Django 4.2.7 on 2023-12-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0004_alter_bankaccount_currency_alter_company_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('PLN', 'PLN'), ('USD', 'USD'), ('CZK', 'CZK')], max_length=3),
        ),
    ]
