# Generated by Django 4.2.7 on 2023-12-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0005_alter_cost_payment_date_alter_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
