# Generated by Django 4.2.7 on 2023-12-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0006_cost_estimated_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pln_gross_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pln_net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
