# Generated by Django 4.2.7 on 2024-01-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0008_alter_invoice_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='category',
            field=models.CharField(blank=True, choices=[('OPERATION', 'OPERATION'), ('MEDIA', 'MEDIA'), ('PRODUCTION', 'PRODUCTION')], max_length=20, null=True),
        ),
    ]
