# Generated by Django 4.2.7 on 2024-01-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0009_cost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cost', to='costs_records.invoice'),
        ),
    ]
