# Generated by Django 4.2.7 on 2024-01-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0011_exchangerate_rete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='rete',
            new_name='rate',
        ),
    ]
