# Generated by Django 4.2.7 on 2024-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0012_rename_rete_exchangerate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(null=True, upload_to='invoices/'),
        ),
    ]
