# Generated by Django 4.2.7 on 2024-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0013_alter_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(),
        ),
    ]
