# Generated by Django 4.2.7 on 2024-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0014_alter_exchangerate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='days_to_due_date',
            field=models.DateField(null=True),
        ),
    ]
