# Generated by Django 4.2.7 on 2024-02-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_records', '0015_invoice_days_to_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='days_to_due_date',
            field=models.IntegerField(null=True),
        ),
    ]
